services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "4000:4000"
    environment:
      PORT: 4000
      JUDGE0_URL: http://judge0-server:2358
    depends_on:
      - judge0-server

  judge0-server:
    image: judge0/judge0:latest
    ports:
      - "2358:2358"
  
  judge0-workers:
    image: judge0/judge0:latest
    command: ["./scripts/workers"]
    scale: 3  # 3 workers cho concurrency